# Generated by Django 4.0.1 on 2022-01-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='Имя пользователя')),
                ('second_name', models.CharField(max_length=200, verbose_name='Фамилия пользователя')),
                ('gender', models.CharField(choices=[('М', 'Мужчина'), ('Ж', 'Женщина')], default='М', max_length=1)),
                ('avatar', models.ImageField(upload_to='', verbose_name='Аватар пользователя')),
            ],
        ),
    ]
